Support SSH proxy over TCP
docksal/image-ssh-agent pull request #8
Opened 2019-06-24 12:43 UTC by GMTA

This adds support for a new `ssh-proxy` mode that instead of running an SSH agent, starts a `socat` process that creates a Unix socket that transparently proxies to a remote TCP endpoint provided as an argument.

This works in conjunction with the following MR for Docksal:
(MR incoming - will edit soon)

The health check uses `DOCKSAL_SSH_AGENT_USE_HOST` to determine whether to check for the built-in SSH agent or not.

2019-08-07 22:26 UTC, lmakarov commented
@GMTA thanks for the PRs! I finally found time to review them.

For the healthcheck, I'd suggest using something like this:

```

#!/usr/bin/env bash
set -eo pipefail

# Get the name of the process with pid=1
docker_cmd=$(cat /proc/1/comm)

# Health checks for ssh-agent mode
if [[ "${docker_cmd}" == "ssh-agent" ]]; then
	netstat -nlp | grep -qE "LISTENING.*${SSH_AUTH_PROXY_SOCK}"
	netstat -nlp | grep -qE "LISTENING.*${SSH_AUTH_SOCK}"
fi

# Health checks for ssh-proxy mode
if [[ "${docker_cmd}" == "ssh-proxy" ]]; then
	netstat -nlp | grep -qE "LISTENING.*${SSH_AUTH_PROXY_SOCK}"
fi
```

This way, the `DOCKSAL_SSH_AGENT_USE_HOST` does not need to be passed to the ssh-agent container (this needs to be updated in https://github.com/docksal/docksal/pull/1088)

2019-08-07 22:26 UTC, lmakarov requested changes
See my previous comment

2019-08-09 15:17 UTC, GMTA commented
Good suggestion! The only change necessary was updating "ssh-proxy" to "socat" since that is the process' name.

2019-08-09 21:21 UTC, lmakarov approved these changes

2019-08-09 21:22 UTC, merged